import { useState } from 'react'
import './App.css'

const projects = [
  { number: '01', title: 'Products Store', description: 'A polished shopping experience with clear browsing and a focused product journey.', tags: ['React', 'CSS'], tone: 'peach', url: 'https://store-ivory-nine.vercel.app/' },
  { number: '02', title: 'Recipes Store', description: 'A friendly recipe collection designed to make discovering your next meal simple.', tags: ['JavaScript', 'Bootstrap'], tone: 'mint', url: 'https://recipes-beta-dun.vercel.app/' },
  { number: '03', title: 'Dashboard', description: 'A focused analytics dashboard for teams that want to see the signal quickly.', tags: ['React', 'JavaScript'], tone: 'lilac', url: 'https://dashboard-alpha-one-76.vercel.app/' },
]

function App() {
  const [sent, setSent] = useState(false)
  const handleSubmit = (event) => { event.preventDefault(); setSent(true) }

  return (
    <div className="site-shell">
      <nav className="navbar navbar-expand-lg site-nav fixed-top" aria-label="Main navigation">
        <div className="container py-3"><a className="navbar-brand d-flex align-items-center gap-2" href="#home"><span className="brand-mark">Y</span><span>Yousof Alaa</span></a><button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#portfolioNav" aria-controls="portfolioNav" aria-label="Toggle navigation"><span className="navbar-toggler-icon" /></button><div className="collapse navbar-collapse" id="portfolioNav"><div className="navbar-nav ms-auto align-items-lg-center gap-lg-4"><a className="nav-link" href="#about">About</a><a className="nav-link" href="#projects">Projects</a><a className="nav-link" href="#contact">Contact</a><a className="btn btn-sm btn-mint ms-lg-3" href="#contact">Let&apos;s talk <span aria-hidden="true">↗</span></a></div></div></div>
      </nav>
      <main>
        <section className="hero py-5" id="home"><div className="container py-lg-5"><div className="row align-items-center g-5"><div className="col-lg-7"><div className="hero-copy"><p className="eyebrow mb-4"><span className="status-dot" /> Available for new opportunities</p><h1 className="display-1 fw-bold mb-4">Building digital <span>experiences</span> with purpose.</h1><p className="lead hero-intro mb-4">I&apos;m Yousof, a front-end developer who turns ideas into thoughtful, fast, and beautifully usable interfaces.</p><div className="d-flex flex-wrap gap-3"><a className="btn btn-lilac btn-lg" href="#projects">See my work <span aria-hidden="true">↓</span></a><a className="btn btn-link btn-lg text-decoration-none" href="mailto:yousofalaa26@gmail.com">Get in touch <span aria-hidden="true">↗</span></a></div></div></div><div className="col-lg-5"><div className="code-card shadow-sm" aria-label="Code preview"><div className="d-flex justify-content-between small text-secondary"><span>yousof.dev</span><span>01 / 04</span></div><div className="code-window mt-5"><span className="code-comment">// turning concepts into interfaces</span><span><b className="code-keyword">const</b> <b className="code-name">developer</b> = {'{'}</span><span className="indent"><i>name:</i> <strong>&apos;Yousof&apos;</strong>,</span><span className="indent"><i>focus:</i> <strong>&apos;front-end&apos;</strong>,</span><span className="indent"><i>curiosity:</i> <strong>true</strong></span><span>{'}'}</span><span className="code-cursor">_</span></div><p className="mb-0 mt-5 fw-bold">Frontend developer <span>✳</span></p></div></div></div></div></section>
        <section className="container py-4"><div className="row g-3 highlights"><div className="col-md-4"><div className="highlight h-100"><small>01 — What I bring</small><strong>Clean code</strong><span>Clear thinking</span></div></div><div className="col-md-4"><div className="highlight h-100"><small>02 — How I work</small><strong>Curiosity first</strong><span>Always learning</span></div></div><div className="col-md-4"><div className="highlight h-100"><small>03 — My focus</small><strong>Human interfaces</strong><span>Details that matter</span></div></div></div></section>
        <section className="container section-space" id="about"><div className="section-kicker"><span>About me</span><span>02</span></div><div className="row g-5 align-items-start pt-5"><div className="col-lg-6"><h2 className="display-5 fw-bold">Good design feels <span>inevitable.</span></h2></div><div className="col-lg-5 offset-lg-1 about-copy"><p>I&apos;m a front-end developer based in Egypt, passionate about making the web more human. I care about the details that turn a functional page into a memorable experience.</p><p>From semantic HTML to component-driven React, I enjoy working across the full interface and leaving every project better than I found it.</p><a className="text-link" href="mailto:yousofalaa26@gmail.com">More about my approach <span>↗</span></a></div></div><div className="toolkit d-flex flex-wrap align-items-center gap-2 mt-5 pt-4"><small className="me-3">My toolkit</small>{['HTML', 'CSS', 'JavaScript', 'Bootstrap', 'React'].map((skill) => <span className="badge skill" key={skill}>{skill}</span>)}</div></section>
        <section className="projects-section section-space" id="projects"><div className="container"><div className="section-kicker"><span>Selected work</span><span>03</span></div><div className="row align-items-end g-4 py-5"><div className="col-lg-7"><h2 className="display-5 fw-bold mb-0">A few things <span>I&apos;ve made.</span></h2></div><div className="col-lg-4 offset-lg-1"><p className="mb-0">A growing collection of interfaces, experiments, and small details that I&apos;m proud of.</p></div></div><div className="row g-4">{projects.map((project) => <div className="col-lg-4" key={project.number}><a className={`project-card ${project.tone} h-100 d-flex flex-column`} href={project.url} target="_blank" rel="noreferrer"><div className="d-flex justify-content-between align-items-center"><span className="project-number">{project.number}</span><span className="project-symbol" aria-hidden="true">↗</span></div><div className="mt-auto pt-5"><h3>{project.title}</h3><p>{project.description}</p><div className="d-flex justify-content-between align-items-end mt-4"><div className="d-flex gap-2 flex-wrap">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><span className="project-arrow">View <span aria-hidden="true">↗</span></span></div></div></a></div>)}</div></div></section>
        <section className="container section-space" id="contact"><div className="section-kicker"><span>Let&apos;s work together</span><span>04</span></div><div className="row g-5 pt-5"><div className="col-lg-6"><h2 className="display-5 fw-bold">Have an idea? <span>Let&apos;s make it real.</span></h2><p className="lead about-copy mt-4">Tell me a little about what you&apos;re building. I&apos;d love to hear it.</p><div className="contact-details mt-4"><a href="mailto:yousofalaa26@gmail.com">yousofalaa26@gmail.com</a><a href="tel:+201111129909">+20 111 112 9909</a></div></div><div className="col-lg-5 offset-lg-1"><form className="contact-form" onSubmit={handleSubmit}><div><label htmlFor="name" className="form-label">Your name</label><input className="form-control" id="name" name="name" required placeholder="John Doe" /></div><div><label htmlFor="email" className="form-label">Email address</label><input className="form-control" id="email" name="email" type="email" required placeholder="john@example.com" /></div><div><label htmlFor="message" className="form-label">Tell me about your project</label><textarea className="form-control" id="message" name="message" required rows="4" placeholder="A few words about the idea..." /></div><button className="btn btn-lilac btn-lg" type="submit">{sent ? 'Message ready ✓' : 'Send a message ↗'}</button></form></div></div></section>
      </main>
      <footer className="site-footer"><div className="container d-flex flex-wrap justify-content-between align-items-center gap-3 py-4"><a className="navbar-brand d-flex align-items-center gap-2" href="#home"><span className="brand-mark">Y</span><span>Yousof Alaa</span></a><small>Designed &amp; built with intention · © 2026</small><div className="footer-links d-flex gap-3"><a href="https://github.com/Yousof999" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/yousof-alaa-8b07783ab/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></footer>
    </div>
  )
}

export default App
